// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEd56vM3qbNWQH-0QV6Z4GJhfzIL3wl4',
    appId: '1:212473328077:web:e61a5bde49629ec405d484',
    messagingSenderId: '212473328077',
    projectId: 'agrispace-11628',
    authDomain: 'agrispace-11628.firebaseapp.com',
    storageBucket: 'agrispace-11628.firebasestorage.app',
    measurementId: 'G-9VM9ZQVV32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFhnUwWt3nDEzFYoFCKwp_zaLDSfvYPB8',
    appId: '1:212473328077:android:fadef5874a1836f205d484',
    messagingSenderId: '212473328077',
    projectId: 'agrispace-11628',
    storageBucket: 'agrispace-11628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGs3wi_85AHqXnEEVAmEPwllRcl9bpTa8',
    appId: '1:212473328077:ios:13011434aa9b2d0a05d484',
    messagingSenderId: '212473328077',
    projectId: 'agrispace-11628',
    storageBucket: 'agrispace-11628.firebasestorage.app',
    iosBundleId: 'com.example.agri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGs3wi_85AHqXnEEVAmEPwllRcl9bpTa8',
    appId: '1:212473328077:ios:13011434aa9b2d0a05d484',
    messagingSenderId: '212473328077',
    projectId: 'agrispace-11628',
    storageBucket: 'agrispace-11628.firebasestorage.app',
    iosBundleId: 'com.example.agri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWEd56vM3qbNWQH-0QV6Z4GJhfzIL3wl4',
    appId: '1:212473328077:web:6afdae8e66f6d98005d484',
    messagingSenderId: '212473328077',
    projectId: 'agrispace-11628',
    authDomain: 'agrispace-11628.firebaseapp.com',
    storageBucket: 'agrispace-11628.firebasestorage.app',
    measurementId: 'G-PH717GZFM2',
  );
}
